### ISSUE TITLE
API down (Heroku Application Error)

### ISSUE THREAD

**Issue by scruti** [davidsantosmerino/filmaffinity-api#6] opened 2019-12-30 21:32 UTC
Hello, I noticed the API went down recently:

Visiting https://filmaffinity-unofficial.herokuapp.com/ (or any endpoint) you get:

![image](https://user-images.githubusercontent.com/1227578/71601515-04714200-2b54-11ea-84dc-1ba2fcab89fb.png)

**Comment by dsantosmerino** [comment] 2019-12-31 09:50
Hey @scruti!

The problem is that we exhausted the free quota for this month. The next dyno type costs 7$/month, I can consider an upgrade if required.

However, I'd like to know more about your use case of this API and understand your requirements. Also, I'd like to know if you and other developers around will be interested in contributing a bit somehow to maintain this stable version.

**Comment by dsantosmerino** [comment] 2019-12-31 10:00
To unblock your development I have upgraded already the dyno. Let me know if find any new error.

**Closed as completed** 2020-05-07 20:34 UTC
